musicNotes/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', HomePageView, name='Home'),
    url(r'chunks/', ChunkView, name='ChunkView'),
    url(r'success_test/$', SuccessTestView, name='SuccessTestView'),
    url(r'formsuccess/$', SuccessFormPageView.as_view(), name="DataSubmitted"),
    url(r'success/$', SuccessPageView.as_view(), name='Success'),
    url(r'accounts/apply/$', SignUpView.as_view(), name="Signup"),
    url(r'accounts/login/$', LoginView.as_view(), name="Login"),
    url(r'^accounts/portal/$', PatientPortalView, name="Portal"),
    url(r'logout/$', logout_user, name="Logout"),
    url(r'^super/', include(admin.site.urls)),
    url(r'^schedule/$', ScheduleView, name="Schedule"),
    url(r'^health_conditions/$', HealthConditionsView, name="Conditions"),
    url(r'^search/$', PatientSearch, name="PatientSearch"),
    url(r'^delete/$', DeleteUser, name="DeleteUser"),
    url(r'^alert/$', AlertSender, name="Alert"),
    url(r'^accounts/portal/view_alerts/$', EmergencyAlerts, name="ViewAlerts"),
    url(r'^accounts/portal/update_account/$', UpdateAccountView, name="Update"),
    url(r'^accounts/portal/view_appts/$', ApptView, name="ViewAppts"),
    url(r'^accounts/portal/view_ApptHistory/$', view_ApptHistory, name="ViewAppHistory"),
    url(r'^accounts/portal/admin/generate$', GenerateStatsView, name="GenerateStats"),
    url(r'^accounts/portal/admin/view_patients$', PatientDataView, name="PatientDataView"),
    url(r'^accounts/portal/admin/scheduled_appts$', ScheduledDoctorAppointments, name="ScheduledDoctorAppointments"),
    url(r'^accounts/portal/admin/resolve_patient_case$', ResolvedPatientAjaxView, name="ResolvedPatientAjaxView"),
    url(r'^accounts/portal/medical_history$', MedicalHistoryView, name="MedicalHistoryView"),
    url(r'^accounts/portal/prescribe$', PrescribeMedicationView, name="PrescribeMedicationView"),
    url(r'^accounts/portal/hsp/approvals$', PatientApprovalView, name="PatientApprovalView"),
    url(r'^accounts/portal/hsp/approvals/approve$', ProcessPatientApproval, name="ProcessPatientApproval"),
    url(r'^delete/(?P<pk>\d+)$', appt_delete, name='delete'),
    url(r'^doctor_delete/(?P<pk>\d+)$', doctor_appt_delete, name='doctor_delete'),
    url(r'^faqs$', FAQView, name="FAQView"),
    url(r'^accounts/portal/clear/$', clear_perscription_notification, name='clear_perscription_notification'),
    url(r'^accounts/portal/admin/view_lab_results$', get_lab_results, name="get_lab_results"),
    url(r'^accounts/portal/admin/all_lab_tests$', display_all_lab_results, name="display_all_lab_results"),
    url(r'^accounts/portal/admin/create_lab_report$', CreateLabReportView, name="CreateLabReportView"),
    url(r'^accounts/portal/admin/delete_lab_report$', delete_lab_results, name="delete_lab_results"),
    url(r'^accounts/portal/admin/edit_lab_report$', edit_lab_results, name="edit_lab_results"),
    url(r'^accounts/portal/admin/view_all_patient_data$', ViewAllPatientData, name="ViewAllPatientData"),
    url(r'^accounts/portal/admin/remove_alert$', RemoveEmergencyAlert, name="RemoveEmergencyAlert"),
    url(r'^accounts/portal/admin/patient_perscriptions$', ViewCurrentPrescriptions, name="ViewCurrentPrescriptions"),
    url(r'^accounts/portal/admin/upload_medical_report$', MedicalReportView, name="MedicalReportView"),
    url(r'^accounts/portal/admin/create_medical_report$', CreateMedicalReportView, name="CreateMedicalReportView"),
    url(r'^accounts/portal/admin/EditMedicalHistory$', EditRelevantPatientMedicalHistory, name="EditRelevantPatientMedicalHistory"),
    # url(r'^accounts/portal/edit_appt_view$', EditAppointmentPatientView, name="EditAppointmentPatientView")
    url(r'^accounts/portal/view_appts_edit/(?P<pk>\d+)$', EditAppointmentPatientView, name="EditAppointmentPatientView"),
    url(r'^accounts/portal/appointment_revision/$', PatientReviseAppointmentView, name="PatientReviseAppointmentView"),
    url(r'^send_appt_update/$', SaveApptEditView, name="SaveApptEditView"),
    url(r'^accounts/portal/upload/$', UploadFile, name="UploadFile"),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

musicNotes/models.py
from django.contrib.auth.models import User
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime

#This class will also contain the list of names of the doctors who work for the hospital
class MusicAdmin(models.Model):
	first_name = models.CharField(max_length=256, default="")
	last_name = models.CharField(max_length=256, default="")
	user = models.OneToOneField(User, unique=True, blank=False, default="", null=False)

	def __unicode__(self):
		return str(self.first_name.title() + ' ' + str(self.last_name.title()))

class PermissionsRole(models.Model):
	role = models.CharField(max_length=256, choices=[('admin', 'admin'), ('patient', 'patient')])
	user = models.OneToOneField(User, unique=True,  blank=True, default="")

	def __unicode__(self):
		return str(self.role)

#This is the mediator for the data that is submitted by the user to the HSP staff
#The data is stored and if admin approves user, then the data will be stored into a patient class
class TempPatientData(models.Model):

	user = models.OneToOneField(User,unique=True,null=True,default="")
	email_address = models.CharField(max_length=256, blank=False)
	first_name = models.CharField(max_length=256, default="")
	last_name = models.CharField(max_length=256, default="")
	age = models.IntegerField(default = 18, blank=False)
	gender = models.CharField(max_length=256, choices=[('male','Male'), ('female', 'Female'), ('other', 'Other'), ('prefer not to say', 'Prefer Not To Say')], default='Select a gender', blank = False)
	data_sent = models.IntegerField(default=0)


	def __unicode__(self):
		return (str(self.first_name) + " " + str(self.last_name) + " " + str(self.email_address))

#This patient model will extend the user class so we can add the associated medical data for the user
class Patient(models.Model):

	fill_from_application = models.OneToOneField(TempPatientData,unique=True,null=True,default="")
	user = models.OneToOneField(User, unique=True,  blank=True, default="", null=True)
	approved = models.IntegerField(default=0, null=False)
	alertSent = models.IntegerField(default=0, null=False)
	date_created = models.CharField(default="9-20-1995", null=True, max_length=20)


	def __unicode__(self):
		return 'Email: ' + str(self.user) + ' First Name: ' + str(self.fill_from_application.first_name) + ' Last Name: ' + str(self.fill_from_application.last_name)

class PatientHealthConditions(models.Model):

	user = models.OneToOneField(Patient, unique=False, blank=True, default="")

	#nausea_level = models.IntegerField(validators=[MinValueValidator(0),
    #                                  MaxValueValidator(10)], default=0)
	def __unicode__(self):
		return str(self.user.user.username)

#Class for the user to schedule appointments for their associated doctor
class PatientAppt(models.Model):
	date = models.CharField(max_length=1000, unique=True)
	doctor = models.ForeignKey(MusicAdmin, unique=False, default=-1)
	pain_level = models.IntegerField(validators=[MinValueValidator(0),
                                       MaxValueValidator(10)], blank=False)
	medical_conditions = models.CharField(max_length=1000, default="None")
	allergies = models.CharField(max_length=1000, default="None")
	user = models.ForeignKey(Patient, unique=False, blank=True, default="")
	current_health_conditions = models.ForeignKey(PatientHealthConditions, unique=False, blank=True, default="", null=True)
	resolved = models.IntegerField(default=0, blank=True)

	def __unicode__(self):
		return str(self.doctor)

#Class that is responsible for housing all of the alerts that are submitted by the user
class Alert(models.Model):
	alert_level = models.IntegerField(default=0, null=False)
	alert_patient = models.OneToOneField(Patient, unique = True, null = True)
	alert_description = models.CharField(max_length=255, default="", null = True, unique=False)

class EMedication(models.Model):
	patient = models.ForeignKey(Patient, null=False, default='', blank=False)
	medication_name = models.CharField(max_length=255, default = '', blank=False, null=False)
	medication_quantity = models.IntegerField(default=0, blank=True, null=True)
	reminder = models.IntegerField(default=0)
	prescribed_by_doctor = models.ForeignKey(MusicAdmin, default="0")

class LabReport(models.Model):
	lab_patient = models.ForeignKey(Patient, default = "0")
	lab_results = models.CharField(max_length=255, choices=[('positive', 'Positive'), ('negative', 'Negative')])
	lab_test = models.CharField(max_length=255, choices=[('Blood pressure screening', 'Blood pressure screening'), ('C-reactive protein test', 'C-reactive protein test'), ('Colonoscopy', 'Colonoscopy'), ('Diabetes risk tests', 'Diabetes risk tests'), ('Pap smear', 'Pap smear'), ('Skin cancer exam', 'Skin cancer exam'), ('Blood Tests', 'Blood Tests')])
	lab_notes = models.TextField(default="Insert Notes For Lab Test")
	

class AddMedicalHistory(models.Model):
	allergies = models.CharField(max_length=255, default="")
	medical_conditions = models.CharField(max_length=255, default="")
	patient = models.ForeignKey(Patient, default="")

templates/_layouts/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'ico/favicon.png' %}">

    <title>IPIMS Solutions</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="{% static 'js/Chart.js' %}"></script>
    <script src="{% static 'js/highcharts.js' %}"></script>
    <script src="{% static 'js/modules/exporting.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/jquery.simple-dtpicker.js' %}"></script>
    <link type="text/css" href="http://mugifly.github.io/jquery-simple-datetimepicker/jquery.simple-dtpicker.css" rel="stylesheet" />
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
    <link href="{% static 'css/card.css' %}" rel="stylesheet">




    <script src="http://code.highcharts.com/maps/modules/map.js"></script>
    <script src="http://code.highcharts.com/maps/modules/data.js"></script>
    <script src="http://code.highcharts.com/mapdata/countries/us/us-all.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

<script>
$(document).ready(function() {
   $('#id_resolved').hide();
   $('label[for="id_resolved"]').hide();
});
</script>

    {% block extension %}{% endblock %}

  </head>
  <body>

    {{ static }}

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">IPIMS S<i class="fa fa-circle">LUTI</i><i class="fa fa-circle">NS</i></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">HOME</a></li>

            {% if not user.is_authenticated %}
            <li><a href="/accounts/apply">APPLY</a></li>
            <li><a href="/accounts/login">LOGIN</a></li>
            {% elif approval == 0 and not user.username == "admin" %}

            <li class="active"><a href="/accounts/portal">CHECK APPROVAL STATUS</a></li>
            <li><a href="/logout">LOGOUT</a></li>
            {% elif user.username == "admin" %}
            <li class="active"><a href="/accounts/portal">ADMIN PORTAL</a></li>
            <li><a href="/logout">LOGOUT</a></li>
            {% else %}
            <li class="active"><a href="/accounts/portal">USER PORTAL</a></li>
            <li><a href="/logout">LOGOUT</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<br>

    <div class="container w">
        {% if user.is_authenticated %}
<!-- <a href="accounts/portal/">Return To The Portal</a> -->
        <a href="/accounts/portal/" class="btnn btn-blue">Return To The Portal</a>
{% endif %}
            {% block content %}{% endblock %}

    </div><!-- container -->



    
    <div id="r">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-8 col-lg-offset-2">
                    <h4>SAVING LIVES AND MANAGING PATIENT CARE IS OUR GOAL.</h4>
                    <p>IPIMS Solutions is dedicated to solving patient problems, understanding user roles, developing efficient strategies and delivering quality content immediately. Our system is the future of hospitals and computing - with a powerful backend system and quality UX experience, IPIMS Solutions is the way for you.</p>
                </div>
            </div><!-- row -->
        </div><!-- container -->
    </div>
    
    
    <!-- FOOTER -->
    <div id="f">
        <div class="container">
            <div class="row centered">
                IPIMS Solutions - 2015
        
            </div><!-- row -->
        </div><!-- container -->
    </div><!-- Footer -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>

</html>